MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ("isic_train",)
  TEST: ("isic_test",)
  #TRAIN: ("voc_2012_train", "voc_2012_val")
  #TEST: ("voc_2012_val",)
SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (12500, )
  MAX_ITER: 17500
  IMS_PER_BATCH: 8
TEST:
  IMS_PER_BATCH: 8

INPUT:
  PIXEL_MEAN: (0.3359, 0.1133, 0.0276)
  PIXEL_STD: (0.3324, 0.3247, 0.3351)
